### ISSUE TITLE
[feat] About the Dataset

### ISSUE THREAD

**Issue by lixiangcog** [aleemsidra/SaLIP#1]
Hello, thank you for your excellent contribution. Could you please upload the organized dataset used in the paper? This would make it easier to load the data in the code.

**Comment by aleemsidra** [comment]
Hi @lixiang007666! thanks for reaching out! SaLIP performs adaptation entirely during inference, so there’s no specific organization to follow. Each of the respective dataset papers has been cited in the paper (go through those for details). You’ll need to download the datasets, select the official test set, and update the`data_path` key in the config file with your local path to the dataset. I’m also including the links to each dataset here  for convenience.

1. **CC359:** https://www.ccdataset.com/download
2. **Chest Xray Masks and Labels:** https://www.kaggle.com/datasets/nikhilpandey360/chest-xray-masks-and-labels/data
3. **HC18:** https://zenodo.org/records/1327317
